insert into event_types (name) values ('Citizen Check In');
insert into event_types (name) values ('Citizen Check Out');
insert into event_types (name) values ('Volunteer Check In');
insert into event_types (name) values ('Volunteer Check Out');
insert into event_types (name) values ('Citizen Temporary Leave ');
insert into event_types (name) values ('Citizen Return');
insert into event_types (name) values ('Created Injury Report');
insert into event_types (name) values ('Referred to Nurse');
insert into event_types (name) values ('Injury Resolved');
insert into event_types (name) values ('Organization Member Check In');
insert into event_types (name) values ('Organization Member Check Out');
insert into event_types (name) values ('Organization Pending');
insert into event_types (name) values ('Organization Approval');
insert into event_types (name) values ('Organization Rejected');
insert into event_types (name) values ('Organization Activated');
insert into event_types (name) values ('Organization Deactivated');
